### ISSUE TITLE
BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#22]
Hi Shern,

I can run the test "dilute" successfully in Linux Cloud with 2 core and 2048 MB RAM. I can also run my system with any compute and fixes such as (compute chunk/atom" and  "fix ave/chunk") only if I try to get only at most 1 interested parameter and also only if I use fix ave/time or fix ave/histo with (Nevery=1, Nrepeat=1, and Nfreq=1)

I mean if I try to use multiple of  (compute chunk/atom" and  "fix ave/chunk") for various atoms or various parameters or if I use fix ave/time or fix ave/histo with for example (Nevery=1, Nrepeat=10, and Nfreq=100), I get the error as below:

*Is it possible to figure out the reason? 
*Is this related to the 2048 MB RAM? How many core and RAM is required at least for a system with 15k atoms and multiple interested parameters such as atom density, RDF, ...

I do appreciate your help

Best regards,

============================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 8040 RUNNING AT vm9532652820.bitcommand.com
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
============================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by srtee** [comment]
Hi there,

I am not sure if you have done this yet, but could you check if your scripts run without the "fix conp" command? This will show if the problem is specific to the fix conp code or to the rest of your script.

It's hard to give more specific ideas without seeing your script. If you would like to attach it here (in the working and non-working versions), that will allow me to give more comments. You can also email me at s.tee@uq.edu.au .

**Comment by saffari101** [comment]
Dear Shern,

Thanks a lot. I will send my files.
