### ISSUE TITLE
Why the electrodes were stretched toward each other?

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#31]
Hello Dear,

I am applying conp2 for a system as I attached its image to this post, but according to image the electrodes were stretched toward each other after some steps, even though I assigned a zero setforce on them. I used ffield with as below. Could you please let me know whether is this because of my selected options in conp fix ?

variable v equal 1.2 
timestep 1

fix fxnve ele nve
fix fxnvt sol nvt temp 295 295 100
fix e eleleft conp 1 eleright 1.979 1.2 iter etypes 2 5 6 pppm ffield
fix efield all efield 0.0 0.0 $(-v_v/lz)

![Capture](https://user-images.githubusercontent.com/17302654/132619178-06b3f05a-c0da-40da-8cbb-157eb2db0a86.JPG)

Bests,

**Comment by srtee** [comment]
Hi,

It is possible that if "fix efield" is in the script after "fix setforce" that the efield is being applied afterwards and imposing a nonzero force on the electrode. Try putting the "fix setforce" command after the "fix efield" command.

Alternatively apply the "fix efield" to only the electrolyte group instead of to "all". Additionally, for maximum safety you can also apply "fix nvt" to only the electrolyte group instead of to "all", so that the electrode atoms do not have an integrator associated with them.

**Comment by saffari101** [comment]
Dear Shern,

Thank you very much for the incredible advises. I made the corrections.

All the bests,
