### ISSUE TITLE
Could this CPM be coupled with ReaxFF? Use them together.

### ISSUE THREAD

**Issue by ms123456-TX** [srtee/lammps-USER-CONP2#34]

**Comment by srtee** [comment]
Hi there,

Without further descriptions, it's hard for me to know exactly what you need to know. My first instinct would be that it is technically possible to use CONP2 and ReaxFF together -- whether it is mathematically and physically correct is a much more difficult question.

Some things to consider:
- CONP2 can have a big memory footprint. This may interfere with ReaxFF.
- CONP2 dynamically resets charges for electrode particles. As far as I know, ReaxFF also resets charges dynamically. You need to specify that ReaxFF (through QEq or some such) will not reset electrode particles charges (otherwise CONP2 is doing all its work for nothing)
- CONP2 assumes that all initially conductive particles remain conductive throughout the simulation. If ReaxFF "reacts" electrode particles, then this is not a # work).

You are more than welcome to try. Just follow the usual best practice with untested combinations of techniques (start with systems as small and simple as possible; compare "augmented" and "baseline" simulations and check that the additional techniques make a big and clear enough difference to be worthwhile; find and track physical observables that will clearly tell you if your simulation results are reasonable or not).

Cheers
Shern

**Comment by ms123456-TX** [comment]
Thanks for your advice. I will try it.

**Comment by ms123456-TX** [comment]
> Hi there,
> 
> The best way to use the issue tracker is to actually try ReaxFF with CONP2 and come back with concrete errors or issues if there are any. "Will ReaxFF work with CONP2" is far too generic.
> 
> Without further descriptions, it's hard for me to know exactly what you need to know. My first instinct would be that it is technically possible to use CONP2 and ReaxFF together -- whether it is mathematically and physically correct is a much more difficult question.
> 
> Some things to consider:
> 
> * CONP2 can have a big memory footprint. This may interfere with ReaxFF.
> * CONP2 dynamically resets charges for electrode particles. As far as I know, ReaxFF also resets charges dynamically. You need to specify that ReaxFF (through QEq or some such) will not reset electrode particles charges (otherwise CONP2 is doing all its work for nothing)
> * CONP2 assumes that all initially conductive particles remain conductive throughout the simulation. If ReaxFF "reacts" electrode particles, then this is not a physically good assumption (even though the code might still work).
> 
> You are more than welcome to try. Just follow the usual best practice with untested combinations of techniques (start with systems as small and simple as possible; compare "augmented" and "baseline" simulations and check that the additional techniques make a big and clear enough difference to be worthwhile; find and track physical observables that will clearly tell you if your simulation results are reasonable or not).
> 
> Cheers Shern

Thanks for your advice. I will try it.
